# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmath.proto\"\x1e\n\x06SumArg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x18\n\tSumResult\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\"\n\x04Math\x12\x1a\n\x03Sum\x12\x07.SumArg\x1a\n.SumResultB\x03\x90\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'math_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _SUMARG._serialized_start=14
  _SUMARG._serialized_end=44
  _SUMRESULT._serialized_start=46
  _SUMRESULT._serialized_end=70
  _MATH._serialized_start=72
  _MATH._serialized_end=106
_builder.BuildServices(DESCRIPTOR, 'math_pb2', globals())
# @@protoc_insertion_point(module_scope)
